//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhDoiTra
    {
        public int MaAnhDoiTra { get; set; }
        public string HinhAnhDoiTra { get; set; }
        public Nullable<int> MaDoiTra { get; set; }
        public string SanPham { get; set; }
    
        public virtual DoiTra DoiTra { get; set; }
    }
}
