//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBinhLuan { get; set; }
        public int MaTaiKhoan { get; set; }
        public int MaSanPham { get; set; }
        public string GiaoHang { get; set; }
        public string DungVoiMoTa { get; set; }
        public string BinhLuan1 { get; set; }
        public Nullable<int> DanhGiaSao { get; set; }
        public Nullable<System.DateTime> NgayBinhLuan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> SoLuotThichBL { get; set; }
        public string AnhBinhLuan { get; set; }
        public string PhimBinhLuan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
