//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoiTra()
        {
            this.AnhDoiTras = new HashSet<AnhDoiTra>();
            this.ChiTietDoiTras = new HashSet<ChiTietDoiTra>();
        }
    
        public int MaDoiTra { get; set; }
        public int MaTaiKhoan { get; set; }
        public int MaHoaDon { get; set; }
        public Nullable<int> MaYeuCau { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhDoiTra> AnhDoiTras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDoiTra> ChiTietDoiTras { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual YeuCauDoiTra YeuCauDoiTra { get; set; }
    }
}
