//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViVanChuyen
    {
        public int MaDVvanChuyen { get; set; }
        public string TenDVvanChuyen { get; set; }
        public string AnhDVvanChuyen { get; set; }
    }
}
