//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoiLuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoiLuong()
        {
            this.SanPham_KhoiLuong = new HashSet<SanPham_KhoiLuong>();
        }
    
        public int MaKhoiLuong { get; set; }
        public Nullable<double> KhoiLuong1 { get; set; }
        public Nullable<int> MaDonViTinh { get; set; }
    
        public virtual DonViTinh DonViTinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham_KhoiLuong> SanPham_KhoiLuong { get; set; }
    }
}
