//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int MaKhuyenMai { get; set; }
        public int MaSanPham { get; set; }
        public string TenKhuyenMai { get; set; }
        public Nullable<double> PhanTramKhuyenMai { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<double> GiaKhuyenMai { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
