//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTichDiem
    {
        public int MaPhieuTichDiem { get; set; }
        public int MaTaiKhoan { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string SoDiem { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
