//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.GioHangs = new HashSet<GioHang>();
            this.KhuyenMais = new HashSet<KhuyenMai>();
            this.SanPham_KhoiLuong = new HashSet<SanPham_KhoiLuong>();
            this.TrangThaiSanPhams = new HashSet<TrangThaiSanPham>();
            this.DanhMucs = new HashSet<DanhMuc>();
            this.Khoes = new HashSet<Kho>();
            this.NhaCungCaps = new HashSet<NhaCungCap>();
        }
    
        public int MaSanPham { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]
        public string TenSanPham { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]

        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]

        public Nullable<System.DateTime> NgayHetHan { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]

        public string HanSuDung { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]

        public string ThanhPhan { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]

        public string LuuY { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]

        public string MoTa { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]

        public string XuaXu { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]
        [Range(1000,10000000000)]
        
        public Nullable<double> GiaGoc { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]
        [Range(1000, 10000000000)]
        
        public Nullable<double> GiaBan { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]

        public string AnhSanPham { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaChucNang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual ChucNang ChucNang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham_KhoiLuong> SanPham_KhoiLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrangThaiSanPham> TrangThaiSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMuc> DanhMucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kho> Khoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhaCungCap> NhaCungCaps { get; set; }
    }
}
