//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan_DiaChi
    {
        public int MaTaiKhoan { get; set; }
        public int MaDiaChi { get; set; }
        public Nullable<bool> MacDinh { get; set; }
    
        public virtual DiaChi DiaChi { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
