//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.DoiTras = new HashSet<DoiTra>();
            this.GioHangs = new HashSet<GioHang>();
            this.LichSuMuaHangs = new HashSet<LichSuMuaHang>();
            this.NhanViens = new HashSet<NhanVien>();
            this.PhieuTichDiems = new HashSet<PhieuTichDiem>();
            this.QuanTriViens = new HashSet<QuanTriVien>();
            this.TaiKhoan_DiaChi = new HashSet<TaiKhoan_DiaChi>();
            this.ThongTinGiaoHangs = new HashSet<ThongTinGiaoHang>();
            this.ViDienTus = new HashSet<ViDienTu>();
        }
    
        public int MaTaiKhoan { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]
        public string TenTaiKhoan { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]
        public string MatKhau { get; set; }
        //[Required(ErrorMessage = "Không được để trống trường này")]
        //[EmailAddress(ErrorMessage = "Vui lòng nhập đúng Email")]
        public string Email { get; set; }
        //[Required(ErrorMessage = "Không được để trống trường này")]
        //[Phone]
        public string SoDienThoai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string Quyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoiTra> DoiTras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuMuaHang> LichSuMuaHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuTichDiem> PhieuTichDiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanTriVien> QuanTriViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan_DiaChi> TaiKhoan_DiaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinGiaoHang> ThongTinGiaoHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViDienTu> ViDienTus { get; set; }
    }
}
