//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangCuaKhanhBang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinGiaoHang
    {
        public int MaThongTinGiaoHang { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public int MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayGiaoDuKien { get; set; }
        public Nullable<System.DateTime> NgayThucGiao { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
